In [3]:
import pandas as pd

In [4]:
df=pd.read_csv('salaries.csv')

In [5]:
df.head(5)

  company                  job     degree  salary_more_then_100k
0  google      sales executive  bachelors                      0
1  google      sales executive    masters                      0
2  google     business manager  bachelors                      1
3  google     business manager    masters                      1
4  google  computer programmer  bachelors                      0

In [17]:
input_data=df.drop('salary_more_then_100k', axis='columns')

In [18]:
target=df['salary_more_then_100k']

In [14]:
#LabelEncoder converts text labels (strings) into numbers
from sklearn.preprocessing import LabelEncoder

In [15]:
## three diffrent object for three column
le_company=LabelEncoder()
le_job=LabelEncoder()
le_degree=LabelEncoder()

In [19]:
# fit()-> learns all uniqe categpries
#transform()->convert into umeric code 
input_data['new_com']=le_company.fit_transform(input_data['company'])
input_data['new_job']=le_job.fit_transform(input_data['job'])
input_data['new_degree']=le_degree.fit_transform(input_data['degree'])

In [20]:
input_data
## Number is decided alphabetically like apple=0 dell=1

       company                  job     degree  new_com  new_job  new_degree
0       google      sales executive  bachelors        2        2           0
1       google      sales executive    masters        2        2           1
2       google     business manager  bachelors        2        0           0
3       google     business manager    masters        2        0           1
4       google  computer programmer  bachelors        2        1           0
5       google  computer programmer    masters        2        1           1
6   abc pharma      sales executive    masters        0        2           1
7   abc pharma  computer programmer  bachelors        0        1           0
8   abc pharma     business manager  bachelors        0        0           0
9   abc pharma     business manager    masters        0        0           1
10    facebook      sales executive  bachelors        1        2           0
11    facebook      sales executive    masters        1        2           1
12    facebook     business manager  bachelors        1        0           0
13    facebook     business manager    masters        1        0           1
14    facebook  computer programmer  bachelors        1        1           0
15    facebook  computer programmer    masters        1        1           1

In [21]:
numeric_input=input_data.drop(['company','job','degree'], axis='columns')

In [22]:
numeric_input.head(4)

   new_com  new_job  new_degree
0        2        2           0
1        2        2           1
2        2        0           0
3        2        0           1

In [23]:
target

0     0
1     0
2     1
3     1
4     0
5     1
6     0
7     0
8     0
9     1
10    1
11    1
12    1
13    1
14    1
15    1
Name: salary_more_then_100k, dtype: int64

In [25]:
from sklearn import tree
model=tree.DecisionTreeClassifier()

In [26]:
model.fit(numeric_input, target)

DecisionTreeClassifier()

In [27]:
model.score(numeric_input, target)

1.0

# Is salary of Google, Computer Engineer, Bachelors degree > 100 k ?

In [28]:
# it is from input_data com-job-degree
# array[0] means he won't get the job
model.predict([[2,1,0]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])

In [29]:
model.predict([[2,1,1]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([1])

In [31]:
model.predict([[0,2,1]])

C:\Users\hp\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(

array([0])